### ISSUE TITLE
JADE ICA crashes

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PyHAT_Point_Spectra_GUI#279]
~~~~Traceback (most recent call last):
  File "C:\Users\rbanderson\Documents\Projects\LIBS PDART\PyHAT_Point_Spectra_GUI\point_spectra_gui\core\MainWindow.py", line 700, in _exceptionLogger
    function()
  File "C:\Users\rbanderson\Documents\Projects\LIBS PDART\PyHAT_Point_Spectra_GUI\point_spectra_gui\core\MainWindow.py", line 675, in runModules
    self.widgetList[modules].run()
  File "C:\Users\rbanderson\Documents\Projects\LIBS PDART\PyHAT_Point_Spectra_GUI\point_spectra_gui\core\DimensionalityReduction.py", line 92, in run
    self.data[datakey].dim_red(col, method, [], params, load_fit)
  File "C:\Users\rbanderson\Documents\Projects\LIBS PDART\PyHAT_Point_Spectra_GUI\point_spectra_gui\util\spectral_data.py", line 64, in dim_red
    self.df, self.dim_red = dim_red.dim_red(self.df, col = col, method = method, params = params, kws = kws, load_fit = load_fit)
  File "C:\Users\rbanderson\Documents\Projects\LIBS PDART\PyHAT\libpyhat\transform\dim_red.py", line 23, in dim_red
    do_dim_red.fit(df[col])
  File "C:\Users\rbanderson\Documents\Projects\LIBS PDART\PyHAT\bin\jade.py", line 36, in fit
    scores = jadeR(X,m = self.n_components)
  File "C:\Users\rbanderson\Documents\Projects\LIBS PDART\PyHAT\bin\jade.py", line 193, in jadeR
    CM = matrix(zeros([m, m * nbcm], dtype=float64))  # Storage for cumulant matrices
TypeError: 'float' object cannot be interpreted as an integer~~~~

**Comment by ryanbanderson** [comment]
Fixed with PR #200 to PyHAT
